/* ============================================================
   PROJECT: Oracle Payroll Analytics
   FILE: 01_create_tables.sql
   DESCRIPTION:
   Creates the main database structure used for payroll,
   employee, department and salary-history analysis.
   ============================================================ */


/* ============================================================
   1. DEPARTMENTS
   ============================================================ */

CREATE TABLE departments (
    department_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name    VARCHAR2(100) NOT NULL,
    location           VARCHAR2(100),

    CONSTRAINT pk_departments
        PRIMARY KEY (department_id),

    CONSTRAINT uq_departments_name
        UNIQUE (department_name)
);


/* ============================================================
   2. POSITIONS
   ============================================================ */

CREATE TABLE positions (
    position_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    position_name      VARCHAR2(100) NOT NULL,
    base_salary        NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_positions
        PRIMARY KEY (position_id),

    CONSTRAINT uq_positions_name
        UNIQUE (position_name),

    CONSTRAINT ck_positions_salary
        CHECK (base_salary >= 0)
);


/* ============================================================
   3. EMPLOYEES
   ============================================================ */

CREATE TABLE employees (
    employee_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_code      VARCHAR2(20) NOT NULL,
    first_name         VARCHAR2(50) NOT NULL,
    last_name          VARCHAR2(100) NOT NULL,
    email              VARCHAR2(150),
    hire_date          DATE NOT NULL,
    termination_date   DATE,
    employment_status  VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    department_id      NUMBER NOT NULL,
    position_id        NUMBER NOT NULL,

    CONSTRAINT pk_employees
        PRIMARY KEY (employee_id),

    CONSTRAINT uq_employees_code
        UNIQUE (employee_code),

    CONSTRAINT uq_employees_email
        UNIQUE (email),

    CONSTRAINT ck_employees_status
        CHECK (
            employment_status IN (
                'ACTIVE',
                'INACTIVE',
                'TERMINATED'
            )
        ),

    CONSTRAINT ck_employees_dates
        CHECK (
            termination_date IS NULL
            OR termination_date >= hire_date
        ),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id),

    CONSTRAINT fk_employees_position
        FOREIGN KEY (position_id)
        REFERENCES positions(position_id)
);


/* ============================================================
   4. PAYROLL PERIODS
   ============================================================ */

CREATE TABLE payroll_periods (
    period_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    period_code        VARCHAR2(20) NOT NULL,
    start_date         DATE NOT NULL,
    end_date           DATE NOT NULL,
    payment_date       DATE NOT NULL,
    period_status      VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,

    CONSTRAINT pk_payroll_periods
        PRIMARY KEY (period_id),

    CONSTRAINT uq_payroll_period_code
        UNIQUE (period_code),

    CONSTRAINT ck_payroll_period_dates
        CHECK (end_date >= start_date),

    CONSTRAINT ck_payroll_period_status
        CHECK (
            period_status IN (
                'OPEN',
                'CLOSED',
                'PAID'
            )
        )
);


/* ============================================================
   5. PAYROLL
   ============================================================ */

CREATE TABLE payroll (
    payroll_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id        NUMBER NOT NULL,
    period_id          NUMBER NOT NULL,
    gross_salary       NUMBER(12,2) NOT NULL,
    deductions         NUMBER(12,2) DEFAULT 0 NOT NULL,
    bonuses            NUMBER(12,2) DEFAULT 0 NOT NULL,
    net_salary         NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_payroll
        PRIMARY KEY (payroll_id),

    CONSTRAINT uq_payroll_employee_period
        UNIQUE (employee_id, period_id),

    CONSTRAINT ck_payroll_gross
        CHECK (gross_salary >= 0),

    CONSTRAINT ck_payroll_deductions
        CHECK (deductions >= 0),

    CONSTRAINT ck_payroll_bonuses
        CHECK (bonuses >= 0),

    CONSTRAINT ck_payroll_net
        CHECK (net_salary >= 0),

    CONSTRAINT fk_payroll_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id),

    CONSTRAINT fk_payroll_period
        FOREIGN KEY (period_id)
        REFERENCES payroll_periods(period_id)
);


/* ============================================================
   6. SALARY HISTORY
   ============================================================ */

CREATE TABLE salary_history (
    salary_history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id        NUMBER NOT NULL,
    effective_date     DATE NOT NULL,
    previous_salary    NUMBER(12,2),
    new_salary         NUMBER(12,2) NOT NULL,
    change_reason      VARCHAR2(200),

    CONSTRAINT pk_salary_history
        PRIMARY KEY (salary_history_id),

    CONSTRAINT ck_salary_history_previous
        CHECK (
            previous_salary IS NULL
            OR previous_salary >= 0
        ),

    CONSTRAINT ck_salary_history_new
        CHECK (new_salary >= 0),

    CONSTRAINT fk_salary_history_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id)
);